---
title: "2020-2021 NBA Data"
author: "Nate Tran"
date: "4/22/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r read in data}
library(tidyverse)
library(readxl)
library(ggrepel)
library(ggpubr)
nba <- read_excel('nba2020-2021 copy.xlsx')
nba <- nba %>%
  filter(games_played > 40)
```


```{r get column names}
nba %>%
  names
```

```{r Win Shares and Usage}
nba %>%
  select(name, team, win_shares, usage_percentage ) %>%
  ggplot() +
  geom_point(mapping = aes(x = usage_percentage, y = win_shares)) +
  geom_hline(yintercept = mean(nba$win_shares), color = "red", linetype = "dashed", alpha=0.5) +
  geom_vline(xintercept =  mean(nba$usage_percentage), color = "red", linetype = "dashed", alpha=0.5) +
  geom_smooth(mapping = aes(x = usage_percentage, y = win_shares), se = FALSE, method = 'lm') 

nba %>%
  ggscatter(x = "usage_percentage", y = "win_shares", 
          add = "reg.line", conf.int = FALSE, 
          cor.coef = TRUE, cor.method = "pearson",
          xlab = "Usage Percentage", ylab = "Win Shares")
  
```

Looking at a player's usage percentage and win shares, there is a moderate correlation between how much a player is used and how many wins they are responsible for. The red lines represent the average value for each stat.


```{r Position PER/Win Shares}
nba %>%
  filter(position == "PG" | position == "SG" | position == "SF" | position == "PF" | position == "C" ) %>%
  group_by(position) %>%
  summarize(PER = mean(player_efficiency_rating), win_shares = mean(win_shares)) %>%
  gather(stat, total, PER:win_shares) %>%
  ggplot() +
  geom_bar(mapping = aes(x = position, y = total, fill = stat), stat = "identity", position = "dodge")
```

Looking at the bar graph, the Center position has the highest average PER and the highest average win shares by position. 

```{r}
nba %>%
  group_by(team) %>%
  summarize(wins = sum(win_shares)) %>%
  View()
```

```{r}
misc <- read_excel('nbateammiscstats.xlsx')
playoffs <- misc %>%
  filter(Team == "Utah Jazz" | Team == "Los Angeles Clippers" | Team == "Phoenix Suns" | Team == "Milwaukee Bucks" | Team == "Philadelphia 76ers" | Team == "Denver Nuggets" | Team == "Brooklyn Nets" | Team == "Los Angeles Lakers" | Team == "Dallas Mavericks" | Team == "Atlanta Hawks" | Team == "New York Knicks"| Team == "Portland Trail Blazers" | Team == "Boston Celtics"| Team == "Memphis Grizzlies"| Team == "Miami Heat"| Team == "Washington Wizards")
playoffs %>%
  ggplot(aes(x = OeFGPct, y = DeFGPct)) +
  #horizontal line with mean EPA
  geom_hline(yintercept = mean(misc$DeFGPct), color = "red", linetype = "dashed", alpha=0.5) +
  #vertical line with mean CPOE
  geom_vline(xintercept =  mean(misc$OeFGPct), color = "red", linetype = "dashed", alpha=0.5) +
  #add points for the QBs with the right colors
  #cex controls point size and alpha the transparency (alpha = 1 is normal)
  geom_point() +
  #add names using ggrepel, which tries to make them not overlap
  geom_text_repel(aes(label=Team)) +
  geom_text(aes(x = mean(misc$OeFGPct), y = .512, label = "NBA Average Offensive eFG%"), vjust = -1, size = 3.5, color = "red") +
  geom_text(aes(y = mean(misc$DeFGPct), x = .565, label = "NBA Average Defensive eFG%"), vjust = -1, size = 3.5, color = "red") +
  #titles and caption
  labs(x = "Offensive Effective FG %",
       y = "Defensive Effective FG %",
       title = "2021 NBA Playoff Teams Effective FG %",
       caption = "Data: @bball_ref | Graph By: Nate Tran | @domiNATEstats") +
  #uses the black and white ggplot theme
  theme_bw() +
  #center title with hjust = 0.5
  theme(
    plot.title = element_text(size = 14, hjust = 0.5, face = "bold")
  ) +
  #make ticks look nice
  #if this doesn't work, `install.packages('scales')`
  scale_y_continuous(breaks = scales::pretty_breaks(n = 10)) +
  scale_x_continuous(breaks = scales::pretty_breaks(n = 10)) +
  ggsave('efgpcts.png')
```

